
CREATE TABLE SUPERUSUARIO (
    ID_SUPERUSUARIO BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    EMAIL_SUPERUSUARIO VARCHAR(50) NOT NULL,
    CONTRASEÑA_SUPERUSUARIO VARCHAR(10) NOT NULL,
    NOMBRE_SUPERUSUARIO VARCHAR(50) NOT NULL
);


CREATE TABLE TALLER (
    ID_TALLER BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,        
    NOMBRE_TALLER VARCHAR(15) NOT NULL ,                 
    DIRECCION_TALLER VARCHAR(100) NOT NULL,          
    COMUNA_TALLER VARCHAR(25) NOT NULL,              
    CIUDAD_TALLER VARCHAR(25) NOT NULL,              
    PAIS_TALLER VARCHAR(15) NOT NULL,                          
    EMAIL_TALLER VARCHAR(25) NOT NULL,               
    CAPACIDAD_TOTAL_TALLER INT,                              
    GERENTE_TALLER VARCHAR(15) NOT NULL,
    TELEFONO_TALLER VARCHAR(15) NOT NULL             
);



CREATE TABLE SUCURSAL(
    ID_SUCURSAL BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NOMBRE_SUCURSAL VARCHAR(50) NOT NULL,
    DIRECCION_SUCURSAL VARCHAR(50) NOT NULL,
    COMUNA_SUCURSAL VARCHAR(50) NOT NULL,
    CIUDAD_SUCURSAL VARCHAR(50) NOT NULL,
    PAIS_SUCURSAL VARCHAR(50) NOT NULL,
    EMAIL_SUCURSAL VARCHAR(50) NOT NULL,
    CAPACIDAD_SUCURSAL INT ,
    TELEFONO_SUCURSAL VARCHAR(50) NOT NULL,
    ID_TALLER BIGINT,
    FOREIGN KEY (ID_TALLER) REFERENCES TALLER(ID_TALLER)
);

CREATE TABLE ESTADO_USUARIO (
    ID_ESTADO_USUARIO BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    DESCRIPCION_ESTADO_USUARIO VARCHAR(50) NOT NULL
);

CREATE TABLE USUARIO (
    ID_USUARIO VARCHAR(8) PRIMARY KEY,
    EMAIL_USUARIO VARCHAR(50) NOT NULL,
    CONTRASEÑA_USUARIO VARCHAR(10) NOT NULL,
    NOMBRE_USUARIO VARCHAR(50) NOT NULL,
    APEP_USUARIO VARCHAR(50) ,
    APEM_USUARIO VARCHAR(50) ,
    CONTACTO_USUARIO VARCHAR(50) NOT NULL,
    F_INGRESO_USUARIO TIMESTAMP DEFAULT NOW() NOT NULL,
    ID_ESTADO_USUARIO BIGINT,
    ID_TALLER BIGINT,
    FOREIGN KEY (ID_ESTADO_USUARIO) REFERENCES ESTADO_USUARIO(ID_ESTADO_USUARIO),
    FOREIGN KEY (ID_TALLER) REFERENCES TALLER(ID_TALLER)
);

CREATE TABLE SUBSCRIPCION (
    ID_SUBSCRIPCION BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    CANTIDAD_PAGO_SUB INT NOT NULL,
    ESTADO_SUB BOOLEAN NOT NULL,
    TIPO_SUB VARCHAR(50) NOT NULL,
    FECHA_INICIO_SUB TIMESTAMP DEFAULT NOW() NOT NULL,
    FECHAR_VENCIMIENTO_SUB DATE NOT NULL
);

CREATE TABLE PAGO (
    ID_PAGO BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    METODO_PAGO VARCHAR(50) NOT NULL,
    CANTIDAD_PAGADA INT NOT NULL,
    FECHA_PAGO TIMESTAMP DEFAULT NOW() NOT NULL
);
 CREATE TABLE MODULO (
    ID_MODULO BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NOMBRE_MODULO VARCHAR(50) NOT NULL
 );

 CREATE TABLE SUBMODULO (
    ID_SUBMODULO BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NOMBRE_SUBMODULO VARCHAR(50) NOT NULL,
    ID_MODULO BIGINT,
    FOREIGN KEY (ID_MODULO) REFERENCES MODULO(ID_MODULO)
 );
 
CREATE TABLE SECCION (
    ID_SECCION BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NOMBRE_SECCION VARCHAR(50) NOT NULL,
    ID_SUBMODULO BIGINT,
    FOREIGN KEY (ID_SUBMODULO) REFERENCES SUBMODULO(ID_SUBMODULO)
);

CREATE TABLE PERMISO (
    ID_PERMISO BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    DESCRIPCION_PERMISO VARCHAR(50) NOT NULL
);

CREATE TABLE SECCION_PERMISO (
    ID_SECCION BIGINT,
    ID_PERMISO BIGINT,
    FOREIGN KEY (ID_SECCION) REFERENCES SECCION(ID_SECCION),
    FOREIGN KEY (ID_PERMISO) REFERENCES PERMISO(ID_PERMISO)
);

CREATE TABLE SECCION_USUARIO (
    ID_SECCION BIGINT,
    ID_USUARIO VARCHAR(8),
    FOREIGN KEY (ID_SECCION) REFERENCES SECCION(ID_SECCION),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE PANTALLAS_USUARIO (
    ID_USUARIO VARCHAR(8),
    ID_MODULO BIGINT,
    ID_SUBMODULO BIGINT,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_MODULO) REFERENCES MODULO(ID_MODULO),
    FOREIGN KEY (ID_SUBMODULO) REFERENCES SUBMODULO(ID_SUBMODULO)
);

CREATE TABLE BAN_USUARIO_PERMISO (
    ID_USUARIO VARCHAR(8),
    ID_PERMISO BIGINT,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_PERMISO) REFERENCES PERMISO(ID_PERMISO)
);

CREATE TABLE USUARIO_SUCURSAL (
    ID_USUARIO VARCHAR(8),
    ID_SUCURSAL BIGINT,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSAL(ID_SUCURSAL)
);

CREATE TABLE TIPO_CLIENTE (
    ID_TIPO_CLIENTE BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESCRIPCION VARCHAR(255) NOT NULL
);

CREATE TABLE ESTADO_CLIENTE (
    ID_ESTADO_CLIENTE BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESCRIPCION VARCHAR(255) NOT NULL
);

CREATE TABLE CLIENTE (
    RUT_CLIENTE VARCHAR(25) PRIMARY KEY,
    NOM_CLIENTE VARCHAR(255) NOT NULL,
    DIRECCION_CLIENTE VARCHAR(255),
    COMUNA_CLIENTE VARCHAR(100),
    CIUDAD_CLIENTE VARCHAR(100),
    PAIS_CLIENTE VARCHAR(100),
    EMAIL_CLIENTE VARCHAR(255),
    OBS_CLIENTE VARCHAR(500),
    TELEFONO_CLIENTE VARCHAR(50),
    ID_SUCURSAL BIGINT,
    ID_TIPO_CLIENTE BIGINT,
    ID_ESTADO_CLIENTE BIGINT,
    ID_TALLER BIGINT,
    FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSAL(ID_SUCURSAL),
    FOREIGN KEY (ID_TIPO_CLIENTE) REFERENCES TIPO_CLIENTE(ID_TIPO_CLIENTE),
    FOREIGN KEY (ID_ESTADO_CLIENTE) REFERENCES ESTADO_CLIENTE(ID_ESTADO_CLIENTE),
    FOREIGN KEY (ID_TALLER) REFERENCES TALLER(ID_TALLER)
);

CREATE TABLE TIPO_VEHICULO (
    ID_TIPO_VEHICULO BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESCRIPCION VARCHAR(255) NOT NULL
);

CREATE TABLE VEHICULO (
    PATENTE_VEHICULO VARCHAR(20) PRIMARY KEY,
    MARCA_VEHICULO VARCHAR(100),
    MODELO_VEHICULO VARCHAR(100),
    AÑO_VEHICULO VARCHAR(4),
    COLOR_VEHICULO VARCHAR(50),
    KILOMETRAJE_VEHICULO VARCHAR(20),
    TIPO_VEHICULO VARCHAR(100),
    NUM_MOTOR_VEHICULO VARCHAR(50),
    OBS_VEHICULO VARCHAR(500),
    RUT_CLIENTE VARCHAR(25),
    ID_TALLER BIGINT,
    FOREIGN KEY (RUT_CLIENTE) REFERENCES CLIENTE(RUT_CLIENTE),
    FOREIGN KEY (ID_TALLER) REFERENCES TALLER(ID_TALLER)
);

CREATE TABLE PRESUPUESTO (
    ID_PRESUPUESTO BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RUT_CLIENTE VARCHAR(20) NOT NULL,
    PLACA_VEHICULO VARCHAR(20) NOT NULL,
    FECHA_CREACION_PRESUPUESTO_GENERAL DATE NOT NULL,
    DIAS_VALIDEZ_PRESUPUESTO_GENERAL INT NOT NULL,
    OBS_PRESUPUESTO_GENERAL VARCHAR(500),
    ID_SUCURSAL BIGINT,
    FOREIGN KEY (RUT_CLIENTE) REFERENCES CLIENTE(RUT_CLIENTE),
    FOREIGN KEY (PLACA_VEHICULO) REFERENCES VEHICULO(PATENTE_VEHICULO),
    FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSAL(ID_SUCURSAL)
);

CREATE TABLE COBROS (
    ID_COBRO BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_PRESUPUESTO BIGINT NOT NULL,
    CANTIDAD_COBRADA_COBROS INT NOT NULL,
    FORMA_PAGO_COBROS VARCHAR(100),
    FECHA_COBRO DATE NOT NULL,
    NUMERO_RECIBO VARCHAR(50),
    FOREIGN KEY (ID_PRESUPUESTO) REFERENCES PRESUPUESTO(ID_PRESUPUESTO)
);

CREATE TABLE DOCUMENTO (
    ID_DOCUMENTO BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DIRECCION_DOCUMENTO VARCHAR(255) NOT NULL
);

CREATE TABLE FIRMA_CLIENTE (
    ID_FIRMA_CLIENTE BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DIRECCION_FIRMA_CLIENTE VARCHAR(255) NOT NULL
);

CREATE TABLE TARIFA_PIEZAS_PINTADAS (
    ID_TARIFA_PIEZAS_PINTADAS BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESCRIPCION_TARIFA_PIEZAS_PINTADAS VARCHAR(255) NOT NULL,
    PRECIO_POR_PIEZA_PINTADA INT NOT NULL,
    ID_SUCURSAL BIGINT NOT NULL,
    FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSAL(ID_SUCURSAL)
);

CREATE TABLE PINTURA_PRESUPUESTADA (
    ID_PINTURA_PRESUPUESTADA BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_PRESUPUESTO BIGINT NOT NULL,
    NOMBRE_PIEZA_PINTADA VARCHAR(255) NOT NULL,
    CANTIDAD_PIEZAS_PINTADAS INT NOT NULL,
    ID_DOCUMENTO BIGINT,
    ID_TARIFA_PIEZAS_PINTADAS BIGINT NOT NULL,
    FOREIGN KEY (ID_PRESUPUESTO) REFERENCES PRESUPUESTO(ID_PRESUPUESTO),
    FOREIGN KEY (ID_DOCUMENTO) REFERENCES DOCUMENTO(ID_DOCUMENTO),
    FOREIGN KEY (ID_TARIFA_PIEZAS_PINTADAS) REFERENCES TARIFA_PIEZAS_PINTADAS(ID_TARIFA_PIEZAS_PINTADAS)
);

CREATE TABLE TARIFA_MANO_DE_OBRA (
    ID_TARIFA_MANO_DE_OBRA BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESCRIPCION_TARIFA_MANO_DE_OBRA VARCHAR(255) NOT NULL,
    PRECIO_POR_PIEZA_MANO_DE_OBRA INT NOT NULL,
    ID_SUCURSAL BIGINT NOT NULL,
    FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSAL(ID_SUCURSAL)
);

CREATE TABLE MANO_DE_OBRA_PRESUPUESTADA (
    ID_MANO_OBRA BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_PRESUPUESTO BIGINT NOT NULL,
    NOMBRE_PIEZA_MANO_DE_OBRA VARCHAR(255) NOT NULL,
    CANTIDAD_PIEZAS_MANO_OBRA INT NOT NULL,
    ID_DOCUMENTO BIGINT,
    ID_TARIFA_MANO_DE_OBRA BIGINT NOT NULL,
    FOREIGN KEY (ID_PRESUPUESTO) REFERENCES PRESUPUESTO(ID_PRESUPUESTO),
    FOREIGN KEY (ID_DOCUMENTO) REFERENCES DOCUMENTO(ID_DOCUMENTO),
    FOREIGN KEY (ID_TARIFA_MANO_DE_OBRA) REFERENCES TARIFA_MANO_DE_OBRA(ID_TARIFA_MANO_DE_OBRA)
);

CREATE TABLE ORDEN_DE_INGRESO (
    ID_ORDEN_INGRESO BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    LLAVE_ORDEN_INGRESO BOOLEAN NOT NULL,
    PERMISO_CIRCULACION_ORDEN_INGRESO BOOLEAN NOT NULL,
    REVISION_TECNICA_ORDEN_INGRESO BOOLEAN NOT NULL,
    SEGURO_OBLIGATORIO_ORDEN_INGRESO BOOLEAN NOT NULL,
    EXTINTOR_ORDEN_INGRESO BOOLEAN NOT NULL,
    BOTIQUIN_ORDEN_INGRESO BOOLEAN NOT NULL,
    TRIANGULO_ORDEN_INGRESO BOOLEAN NOT NULL,
    RUEDA_REPUESTO_ORDEN_INGRESO BOOLEAN NOT NULL,
    GATA_ORDEN_INGRESO BOOLEAN NOT NULL,
    BARROTE_ORDEN_INGRESO BOOLEAN NOT NULL,
    DADO_SEGURIDAD_ORDEN_INGRESO BOOLEAN NOT NULL,
    HERRAMIENTAS_SEGURIDAD_ORDEN_INGRESO BOOLEAN NOT NULL,
    ENCENDEDOR_ORDEN_INGRESO BOOLEAN NOT NULL,
    PARLANTE_ORDEN_INGRESO BOOLEAN NOT NULL,
    LLANTAS_ORDEN_INGRESO BOOLEAN NOT NULL,
    PISOS_ORDEN_INGRESO BOOLEAN NOT NULL,
    TAG_ORDEN_INGRESO BOOLEAN NOT NULL,
    RADIO_ORDEN_INGRESO BOOLEAN NOT NULL,
    PANEL_ORDEN_INGRESO BOOLEAN NOT NULL,
    PANEL_RADIO_ORDEN_INGRESO BOOLEAN NOT NULL,
    ALZAVIDRIOS_ORDEN_INGRESO BOOLEAN NOT NULL,
    CIERRE_CENTRALIZADO_ORDEN_INGRESO BOOLEAN NOT NULL,
    ESPEJOS_ELECTRICOS_ORDEN_INGRESO BOOLEAN NOT NULL,
    ANTENA_ORDEN_INGRESO BOOLEAN NOT NULL,
    ALARMA_ORDEN_INGRESO BOOLEAN NOT NULL,
    AIRE_ACONDICIONADO_ORDEN_INGRESO BOOLEAN NOT NULL,
    AIRE_ACONDICIONADO_TRASERO_ORDEN_INGRESO BOOLEAN NOT NULL,
    PARABRISAS_ORDEN_INGRESO BOOLEAN NOT NULL,
    LIMPIA_PARABRISAS_ORDEN_INGRESO BOOLEAN NOT NULL,
    LUCES_BAJAS_ORDEN_INGRESO BOOLEAN NOT NULL,
    LUCES_ALTAS_ORDEN_INGRESO BOOLEAN NOT NULL,
    LUCES_TRASERAS_ORDEN_INGRESO BOOLEAN NOT NULL,
    LUCES_ESTACIONAMIENTO_ORDEN_INGRESO BOOLEAN NOT NULL,
    SENSORES_RETROCESO_ORDEN_INGRESO BOOLEAN NOT NULL,
    CAMARA_RETROCESO_ORDEN_INGRESO BOOLEAN NOT NULL,
    NIVEL_COMBUSTIBLE_ORDEN_INGRESO VARCHAR(50) NOT NULL,
    PANTALLA_INTERIOR_ORDEN_INGRESO BOOLEAN NOT NULL,
    OBSERVACIONES_ORDEN_INGRESO BOOLEAN NOT NULL,
    ID_PRESUPUESTO BIGINT NOT NULL,
    FOREIGN KEY (ID_PRESUPUESTO) REFERENCES PRESUPUESTO(ID_PRESUPUESTO)
);


CREATE TABLE ORDEN_DE_TRABAJO (
    ID_ORDEN_TRABAJO BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_ORDEN_INGRESO BIGINT NOT NULL,
    PATENTE_VEHICULO VARCHAR(20) NOT NULL,
    FOREIGN KEY (ID_ORDEN_INGRESO) REFERENCES ORDEN_DE_INGRESO(ID_ORDEN_INGRESO),
    FOREIGN KEY (PATENTE_VEHICULO) REFERENCES VEHICULO(PATENTE_VEHICULO)
);

CREATE TABLE RECEPCION_ACTIVA (
    ID_RECEPCION_ACTIVA BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_ORDEN_INGRESO BIGINT NOT NULL,
    ID_FIRMA_CLIENTE BIGINT NOT NULL,
    ID_PRESUPUESTO BIGINT NOT NULL,
    ID_ORDEN_TRABAJO BIGINT NOT NULL,
    FOREIGN KEY (ID_ORDEN_INGRESO) REFERENCES ORDEN_DE_INGRESO(ID_ORDEN_INGRESO),
    FOREIGN KEY (ID_FIRMA_CLIENTE) REFERENCES FIRMA_CLIENTE(ID_FIRMA_CLIENTE),
    FOREIGN KEY (ID_PRESUPUESTO) REFERENCES PRESUPUESTO(ID_PRESUPUESTO),
    FOREIGN KEY (ID_ORDEN_TRABAJO) REFERENCES ORDEN_DE_TRABAJO(ID_ORDEN_TRABAJO)
);

CREATE TABLE CAMBIOS_PERMITIDOS (
    ID_CAMBIO_PERMITIDO BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESCRIPCION_CAMBIO_PERMITIDO VARCHAR(255) NOT NULL
);

CREATE TABLE CAMBIO_REGISTRADO (
    ID_CAMBIO_REGISTRADO BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_USUARIO VARCHAR(100) NOT NULL,
    FECHA_CAMBIO_REGISTRADO DATE NOT NULL,
    ID_CAMBIO_PERMITIDO BIGINT NOT NULL,
    FOREIGN KEY (ID_CAMBIO_PERMITIDO) REFERENCES CAMBIOS_PERMITIDOS(ID_CAMBIO_PERMITIDO)
);

CREATE TABLE HISTORIAL_ORDEN_DE_INGRESO (
    ID_CAMBIO_REGISTRADO BIGINT NOT NULL,
    ID_ORDEN_INGRESO BIGINT NOT NULL,
    PRIMARY KEY (ID_CAMBIO_REGISTRADO, ID_ORDEN_INGRESO),
    FOREIGN KEY (ID_CAMBIO_REGISTRADO) REFERENCES CAMBIO_REGISTRADO(ID_CAMBIO_REGISTRADO),
    FOREIGN KEY (ID_ORDEN_INGRESO) REFERENCES ORDEN_DE_INGRESO(ID_ORDEN_INGRESO)
);

CREATE TABLE HISTORIAL_ORDEN_DE_TRABAJO (
    ID_CAMBIO_REGISTRADO BIGINT NOT NULL,
    ID_ORDEN_TRABAJO BIGINT NOT NULL,
    PRIMARY KEY (ID_CAMBIO_REGISTRADO, ID_ORDEN_TRABAJO),
    FOREIGN KEY (ID_CAMBIO_REGISTRADO) REFERENCES CAMBIO_REGISTRADO(ID_CAMBIO_REGISTRADO),
    FOREIGN KEY (ID_ORDEN_TRABAJO) REFERENCES ORDEN_DE_TRABAJO(ID_ORDEN_TRABAJO)
);

CREATE TABLE COMISION_DESABOLLADURA (
    ID_COMISION_DESABOLLADURA BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESCRIPCION_COMISION_DESABOLLADURA VARCHAR(255) NOT NULL,
    PORCENTAJE_COMISION_DESABOLLADURA INT NOT NULL,
    ID_SUCURSAL BIGINT NOT NULL,
    FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSAL(ID_SUCURSAL)
);

CREATE TABLE DETALLE_DESABOLLADURA (
    ID_DETALLE_DESABOLLADURA BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RUT_EMPLEADO VARCHAR(50) NOT NULL,
    PAGO_TOTAL_DETALLE_DESABOLLADURA INT NOT NULL,
    DESCRIPCION_TRABAJO_DESABOLLADURA VARCHAR(255) NOT NULL,
    ID_COMISION_DESABOLLADURA BIGINT NOT NULL,
    ID_ORDEN_TRABAJO BIGINT NOT NULL,
    FOREIGN KEY (ID_COMISION_DESABOLLADURA) REFERENCES COMISION_DESABOLLADURA(ID_COMISION_DESABOLLADURA),
    FOREIGN KEY (ID_ORDEN_TRABAJO) REFERENCES ORDEN_DE_TRABAJO(ID_ORDEN_TRABAJO)
);

CREATE TABLE COMISION_PINTURA (
    ID_COMISION_PINTURA BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESCRIPCION_COMISION_PINTURA VARCHAR(255) NOT NULL,
    PRECIO_PIEZA_TRABAJADA INT NOT NULL,
    ID_SUCURSAL BIGINT NOT NULL,
    FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSAL(ID_SUCURSAL)
);

CREATE TABLE DETALLE_PINTURA (
    ID_DETALLE_PINTURA BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RUT_EMPLEADO VARCHAR(50) NOT NULL,
    CANTIDAD_PIEZAS_TRABAJADAS INT NOT NULL,
    DESCRIPCION_TRABAJO_PINTURA VARCHAR(255) NOT NULL,
    ID_COMISION_PINTURA BIGINT NOT NULL,
    ID_ORDEN_TRABAJO BIGINT NOT NULL,
    FOREIGN KEY (ID_COMISION_PINTURA) REFERENCES COMISION_PINTURA(ID_COMISION_PINTURA),
    FOREIGN KEY (ID_ORDEN_TRABAJO) REFERENCES ORDEN_DE_TRABAJO(ID_ORDEN_TRABAJO)
);

CREATE TABLE INSUMO (
    ID_INSUMO BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESCRIPCION_INSUMO VARCHAR(255) NOT NULL,
    FORMATO_INSUMO VARCHAR(50),
    CADUCIDAD_INSUMO DATE,
    PRECIO_INSUMO INT,
    STOCK_MINIMO_INSUMO INT,
    STOCK_MAXIMO_INSUMO INT,
    STOCK_CRITICO_INSUMO INT,
    ID_SUCURSAL BIGINT NOT NULL,
    FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSAL(ID_SUCURSAL)
);

CREATE TABLE CONSUMO_ORDEN_DE_TRABAJO_DESABOLLADURA (
    ID_CONSUMO_OT BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_DETALLE_DESABOLLADURA BIGINT NOT NULL,
    ID_INSUMO BIGINT NOT NULL,
    CANTIDAD_CONSUMIDA INT NOT NULL,
    FOREIGN KEY (ID_DETALLE_DESABOLLADURA) REFERENCES DETALLE_DESABOLLADURA(ID_DETALLE_DESABOLLADURA),
    FOREIGN KEY (ID_INSUMO) REFERENCES INSUMO(ID_INSUMO)
);

CREATE TABLE CONSUMO_ORDEN_DE_TRABAJO_PINTURA (
    ID_CONSUMO_OT BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_DETALLE_PINTURA BIGINT NOT NULL,
    ID_INSUMO BIGINT NOT NULL,
    CANTIDAD_CONSUMIDA INT NOT NULL,
    FOREIGN KEY (ID_DETALLE_PINTURA) REFERENCES DETALLE_PINTURA(ID_DETALLE_PINTURA),
    FOREIGN KEY (ID_INSUMO) REFERENCES INSUMO(ID_INSUMO)
);

CREATE TABLE CARGO (
    ID_CARGO BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOM_CARGO VARCHAR(255) NOT NULL,
    DESCRIPCION_CARGO VARCHAR(500),
    PAGO_CARGO INT NOT NULL
);

CREATE TABLE EMPLEADO (
    RUT_EMPLEADO VARCHAR(50) PRIMARY KEY,
    ID_TALLER BIGINT NOT NULL,
    NOMBRE_EMPLEADO VARCHAR(255) NOT NULL,
    DIRECCION_EMPLEADO VARCHAR(255),
    COMUNA_EMPLEADO VARCHAR(100),
    CIUDAD_EMPLEADO VARCHAR(100),
    NACIONALIDAD_EMPLEADO VARCHAR(100),
    FECHA_NACIMIENTO_EMPLEADO DATE,
    ESTADO_CIVIL_EMPLEADO VARCHAR(50),
    GRUPO_SANGUINEO_EMPLEADO VARCHAR(50),
    TELEFONO_EMPLEADO VARCHAR(20),
    TELEFONO_EMERGENCIA_EMPLEADO VARCHAR(20),
    PREVISION_SALUD_EMPLEADO VARCHAR(50),
    AFP_EMPLEADO VARCHAR(50),
    EMAIL_EMPLEADO VARCHAR(100),
    OBSERVACIONES_EMPLEADO VARCHAR(500),
    ID_CARGO BIGINT NOT NULL,
    FOREIGN KEY (ID_TALLER) REFERENCES TALLER(ID_TALLER),
    FOREIGN KEY (ID_CARGO) REFERENCES CARGO(ID_CARGO)
);

CREATE TABLE TIPO_CONTRATO (
    ID_TIPO_CONTRATO BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESCRIPCION VARCHAR(255) NOT NULL
);

CREATE TABLE FIRMA_EMPLEADO (
    ID_FIRMA_EMPLEADO BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DIRECCION_FIRMA_EMPLEADO VARCHAR(255) NOT NULL
);

CREATE TABLE CONTRATO (
    ID_CONTRATO BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_EMPLEADO VARCHAR(50) NOT NULL,
    ID_TIPO_CONTRATO BIGINT NOT NULL,
    REMUNERACION_CONTRATO INT NOT NULL,
    ID_FIRMA_EMPLEADO BIGINT NOT NULL,
    ID_DOCUMENTO BIGINT NOT NULL,
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(RUT_EMPLEADO),
    FOREIGN KEY (ID_TIPO_CONTRATO) REFERENCES TIPO_CONTRATO(ID_TIPO_CONTRATO),
    FOREIGN KEY (ID_FIRMA_EMPLEADO) REFERENCES FIRMA_EMPLEADO(ID_FIRMA_EMPLEADO),
    FOREIGN KEY (ID_DOCUMENTO) REFERENCES DOCUMENTO(ID_DOCUMENTO)
);


CREATE TABLE TIPO_PROVEEDOR (
    ID_TIPO_PROVEEDOR BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    DESCRIPCION_TIPO_PROVEEDOR VARCHAR(255) NOT NULL
);


CREATE TABLE PROVEEDOR (
    RUT_PROVEEDOR BIGINT NOT NULL,
    ID_TALLER BIGINT NOT NULL,
    RAZON_SOCIAL_PROVEEDOR VARCHAR(255) NOT NULL,
    GIRO_PROVEEDOR VARCHAR(255),
    DIRECCION_PROVEEDOR VARCHAR(255),
    TELEFONO_PROVEEDOR VARCHAR(50),
    EMAIL_PROVEEDOR VARCHAR(255),
    PERSONA_CONTACTO_PROVEEDOR VARCHAR(255),
    PAGINA_WEB_PROVEEDOR VARCHAR(255),
    ID_TIPO_PROVEEDOR BIGINT NOT NULL,
    PRIMARY KEY (RUT_PROVEEDOR, ID_TALLER),
    FOREIGN KEY (ID_TIPO_PROVEEDOR) REFERENCES TIPO_PROVEEDOR(ID_TIPO_PROVEEDOR),
    FOREIGN KEY (ID_TALLER) REFERENCES TALLER(ID_TALLER)
);


CREATE TABLE NOTIFICACIONES (
    ID_NOTIFICACION BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    TITULO_NOTIFICACION VARCHAR(255) NOT NULL,
    DESCRIPCION_NOTIFICACION VARCHAR(500),
    ASUNTO_NOTIFICACION VARCHAR(255),
    FECHA_CREACION_NOTIFICACION TIMESTAMP DEFAULT NOW() NOT NULL
);

CREATE TABLE USUARIO_NOTIFICACION (
    ID_USUARIO VARCHAR(8),
    ID_NOTIFICACION BIGINT,
    VISIBILIDAD_NOTIFICACION BOOLEAN NOT NULL,
    TIEMPO_ESPERA_NOTIFICACION VARCHAR(255),
    PRIMARY KEY (ID_USUARIO, ID_NOTIFICACION),
    FOREIGN KEY (ID_NOTIFICACION) REFERENCES NOTIFICACIONES(ID_NOTIFICACION)
);




INSERT INTO ESTADO_USUARIO (DESCRIPCION_ESTADO_USUARIO)
VALUES ('Activo');

INSERT INTO TALLER (
    NOMBRE_TALLER,
    DIRECCION_TALLER,
    COMUNA_TALLER,
    CIUDAD_TALLER,
    PAIS_TALLER,
    EMAIL_TALLER,
    CAPACIDAD_TOTAL_TALLER,
    GERENTE_TALLER,
    TELEFONO_TALLER
) VALUES (
    'KronosDetail',
    'Av. Principal 123',
    'Comuna Ejemplo',
    'Ciudad Ejemplo',
    'Chile',
    'kronos@detail.com',
    50, -- Capacidad total del taller
    'Juan Perez', -- Nombre del gerente
    '+56912345678' -- Teléfono del taller
);

INSERT INTO USUARIO (
    ID_USUARIO, 
    EMAIL_USUARIO, 
    CONTRASEÑA_USUARIO, 
    NOMBRE_USUARIO, 
    APEP_USUARIO, 
    APEM_USUARIO, 
    CONTACTO_USUARIO, 
    F_INGRESO_USUARIO, 
    ID_ESTADO_USUARIO, 
    ID_TALLER
) VALUES (
    'USR001', 
    'jocsan.riquelme.m@gmail.com', 
    '12345678', -- Reemplaza con un hash cifrado si es necesario
    'Jocsan', 
    'Riquelme', 
    'Mella', 
    '+56931130363', 
    NOW(), 
    1, -- ID de estado de usuario, debe existir en la tabla ESTADO_USUARIO
    1  -- ID de taller, debe existir en la tabla TALLER
);

select * from permiso 


ALTER TABLE USUARIO 
ALTER COLUMN CONTRASEÑA_USUARIO TYPE VARCHAR(60);

UPDATE USUARIO 
SET CONTRASENA_USUARIO = '12345678'
WHERE EMAIL_USUARIO = 'jocsan.riquelme.m@gmail.com';




select * from usuario 

ALTER TABLE TALLER
ALTER COLUMN NOMBRE_TALLER TYPE VARCHAR(50),
ALTER COLUMN DIRECCION_TALLER TYPE VARCHAR(255),
ALTER COLUMN COMUNA_TALLER TYPE VARCHAR(50),
ALTER COLUMN CIUDAD_TALLER TYPE VARCHAR(50),
ALTER COLUMN PAIS_TALLER TYPE VARCHAR(50),
ALTER COLUMN EMAIL_TALLER TYPE VARCHAR(100),
ALTER COLUMN GERENTE_TALLER TYPE VARCHAR(50),
ALTER COLUMN TELEFONO_TALLER TYPE VARCHAR(20);


UPDATE TALLER
SET 
    NOMBRE_TALLER = 'Kronos Automotriz',
    DIRECCION_TALLER = 'Santa Sofia 337',
    COMUNA_TALLER = 'Concepcion',
    CIUDAD_TALLER = 'Concepcion',
    PAIS_TALLER = 'Chile',
    EMAIL_TALLER = 'contacto@kronosdetail.cl',
    CAPACIDAD_TOTAL_TALLER = 50,
    GERENTE_TALLER = 'Marcos Roa',
    TELEFONO_TALLER = '966602828'
WHERE ID_TALLER = 1;

INSERT INTO SUCURSAL (
    NOMBRE_SUCURSAL, 
    DIRECCION_SUCURSAL, 
    COMUNA_SUCURSAL, 
    CIUDAD_SUCURSAL, 
    PAIS_SUCURSAL, 
    EMAIL_SUCURSAL, 
    CAPACIDAD_SUCURSAL, 
    TELEFONO_SUCURSAL, 
    ID_TALLER
) 
VALUES (
    'Kronos Santa Sofia', 
    'Santa Sofia 337', 
    'Concepcion', 
    'Concepcion', 
    'Chile', 
    'contacto@kronosdetail.cl', 
    50, 
    '96662828', 
    1
);


INSERT INTO USUARIO (
    ID_USUARIO,
    EMAIL_USUARIO,
    CONTRASENA_USUARIO,
    NOMBRE_USUARIO,
    APEP_USUARIO,
    APEM_USUARIO,
    CONTACTO_USUARIO,
    F_INGRESO_USUARIO,
    ID_ESTADO_USUARIO,
    ID_TALLER
) 
VALUES
    ('USER_1', 'mroa@kronosdetail.cl', 'Kronos2020.', 'Marcos', 'Roa', 'Ocampos', '985820285', '2023-03-17', 1, 1),
    ('USER_2', 'jsaez@kronosdetail.cl', 'Kronos2020.', 'Jonathan', 'Sáez', 'Rocha', '996109401', '2023-03-13', 1, 1),
    ('USER_3', 'ejecutivo@kronosdetail.cl', 'Kronos2020.', 'Rosse', 'Inestroza', 'López', '928347125', '2023-01-02', 1, 1),
    ('USER_4', 'administracion@kronosdetail.cl', 'Kronos2020.', 'Jaasiel', 'Lepe', 'Concha', '939429265', '2022-06-06', 1, 1);

UPDATE USUARIO
SET ID_USUARIO = 'USER_0'
WHERE ID_USUARIO = 'USR001';



INSERT INTO modulo (nombre_modulo) VALUES ('GESTION');

INSERT INTO SUBMODULO (ID_MODULO, NOMBRE_SUBMODULO) VALUES (1, 'CLIENTES');
INSERT INTO SECCION (ID_SUBMODULO, NOMBRE_SECCION)
VALUES (1, 'NUEVO CLIENTE'), (1, 'LISTA DE CLIENTES'), (1, 'MANEJO DE CLIENTES');
INSERT INTO PERMISO (DESCRIPCION_PERMISO) 
VALUES ('CREAR CLIENTE'), ('CREAR VEHICULO'),('BUSCAR CLIENTE'), ('BUSCAR VEHICULO'), ('EXPORTAR CLIENTES');

INSERT INTO SECCION_PERMISO VALUES (1,1), (1,2);
INSERT INTO SECCION_PERMISO VALUES (2,3);
INSERT INTO SECCION_PERMISO VALUES (3,5);

SELECT * FROM SECCION_PERMISO
SELECT * FROM PERMISO
SELECT * FROM SECCION

INSERT INTO SUBMODULO (ID_MODULO, NOMBRE_SUBMODULO) VALUES (1, 'VEHICULOS');
INSERT INTO SECCION (ID_SUBMODULO, NOMBRE_SECCION)
VALUES (2, 'NUEVO VEHICULO'), (2, 'LISTA DE VEHICULOS');
INSERT INTO SECCION_PERMISO VALUES (4,2), (4,3);
INSERT INTO SECCION_PERMISO VALUES (5,4);


INSERT INTO SUBMODULO (ID_MODULO, NOMBRE_SUBMODULO) VALUES (1, 'PROVEEDORES');

INSERT INTO SECCION (ID_SUBMODULO, NOMBRE_SECCION)
VALUES (3, 'NUEVO PROVEEDOR'), (3, 'LISTA DE PROVEEDORES');
INSERT INTO PERMISO (DESCRIPCION_PERMISO)
VALUES ('CREAR PROVEEDOR'),('BUCAR PROVEEDOR');
INSERT INTO SECCION_PERMISO VALUES (6,6), (7,7);


INSERT INTO modulo (nombre_modulo) VALUES ('TALLER');
INSERT INTO SUBMODULO (ID_MODULO, NOMBRE_SUBMODULO) VALUES (2, 'PRESUPUESTOS');


INSERT INTO ESTADO_USUARIO (DESCRIPCION_ESTADO_USUARIO) VALUES ('Inactivo'); 


INSERT INTO USUARIO_SUCURSAL (ID_USUARIO, ID_SUCURSAL) VALUES 
('USER_1', 1),('USER_2', 1),('USER_3', 1), ('USER_4', 1),('USER_0', 1);


INSERT INTO TALLER (NOMBRE_TALLER, DIRECCION_TALLER, COMUNA_TALLER, CIUDAD_TALLER, PAIS_TALLER, EMAIL_TALLER, CAPACIDAD_TOTAL_TALLER, GERENTE_TALLER, TELEFONO_TALLER)
VALUES 
('TallerPrueba', 'Av. Principal 123', 'Centro', 'Santiago', 'Chile', 'contacto@kronostech.cl', 100, 'Marcos', '987654321'),
('AutoPro', 'Calle Secundaria 456', 'Providencia', 'Santiago', 'Chile', 'info@autopro.cl', 50, 'Luis', '912345678');

INSERT INTO SUCURSAL (NOMBRE_SUCURSAL, DIRECCION_SUCURSAL, COMUNA_SUCURSAL, CIUDAD_SUCURSAL, PAIS_SUCURSAL, EMAIL_SUCURSAL, CAPACIDAD_SUCURSAL, TELEFONO_SUCURSAL, ID_TALLER)
VALUES 
('Sucursal Central', 'Av. Principal 123', 'Centro', 'Santiago', 'Chile', 'central@kronostech.cl', 50, '987654321', 6),
('Sucursal Norte', 'Calle Norte 789', 'Recoleta', 'Santiago', 'Chile', 'norte@kronostech.cl', 30, '912345678', 6),
('Sucursal AutoPro', 'Calle Secundaria 456', 'Providencia', 'Santiago', 'Chile', 'autopro@autopro.cl', 40, '912345678', 7);

INSERT INTO USUARIO (ID_USUARIO, EMAIL_USUARIO, CONTRASENA_USUARIO, NOMBRE_USUARIO, APEP_USUARIO, APEM_USUARIO, CONTACTO_USUARIO, F_INGRESO_USUARIO, ID_ESTADO_USUARIO, ID_TALLER)
VALUES 
('USER_5', 'admin@kronostech.cl', 'admin123', 'Admin', 'Tech', NULL, '777777777', DEFAULT, 1, 6),
('USER_6', 'empleado@kronostech.cl', 'emple123', 'Empleado', 'Sucursal', 'Central', '888888888', DEFAULT, 1, 6),
('USER_7', 'luis@autopro.cl', 'auto123', 'Luis', 'Auto', NULL, '777777777', DEFAULT, 1, 7);

INSERT INTO USUARIO_SUCURSAL (ID_USUARIO, ID_SUCURSAL)
VALUES 
('USER_5', 11), ('USER_5', 12), ('USER_6', 11),('USER_7', 13) ; 


INSERT INTO SECCION_USUARIO (ID_SECCION, ID_USUARIO)
VALUES
(1, 'USER_0'),
(2, 'USER_0'),
(3, 'USER_0'),
(4, 'USER_0'),
(5, 'USER_0'),
(6, 'USER_0'),
(7, 'USER_0');

INSERT INTO SECCION_USUARIO (ID_SECCION, ID_USUARIO)
VALUES
(1, 'USER_1'),
(2, 'USER_1');

INSERT INTO PANTALLAS_USUARIO (ID_USUARIO, ID_MODULO, ID_SUBMODULO)
VALUES
('USER_0', 1, 1),('USER_0', 1, 2),('USER_0', 1, 3),('USER_0', 2, 4)

INSERT INTO PANTALLAS_USUARIO (ID_USUARIO, ID_MODULO, ID_SUBMODULO)
VALUES
('USER_1', 1, 1),('USER_1', 1, 2);

INSERT INTO ESTADO_CLIENTE (DESCRIPCION)
VALUES 
    ('Activo'),
    ('Inactivo');


INSERT INTO TIPO_CLIENTE (DESCRIPCION)
VALUES 
    ('Sin definir'),
    ('Particular'),
    ('Empresa'),
    ('Independiente');

 INSERT INTO TIPO_VEHICULO (DESCRIPCION) VALUES
('Automóvil'),
('Motocicleta'),
('Camión'),
('Bus'),
('Furgón'),
('Tractor'),
('Remolque'),
('Camioneta'),
('Crossover'),
('SUV'),
('Convertible'),
('Deportivo'),
('Minivan'),
('Coupe');


INSERT INTO CLIENTE (
    RUT_CLIENTE, NOM_CLIENTE, TIPO_CLIENTE, DIRECCION_CLIENTE, COMUNA_CLIENTE, 
    CIUDAD_CLIENTE, PAIS_CLIENTE, EMAIL_CLIENTE, OBS_CLIENTE, TELEFONO_CLIENTE, 
    ID_SUCURSAL, ID_TIPO_CLIENTE, ID_ESTADO_CLIENTE, ID_TALLER
) VALUES 
('12345678-1', 'Juan Pérez', '2', 'Calle Principal 123', 'Concepción', 'Concepción', 'Chile', 'juan.perez@gmail.com', 'Cliente regular', '912345678', 1, 2, 1, 1),
('23456789-2', 'María López', '3', 'Av. Las Flores 456', 'Talca', 'Talca', 'Chile', 'maria.lopez@hotmail.com', 'Primer cliente', '922345678', 1, 3, 1, 1),
('34567890-3', 'Carlos García', '1', 'Camino Real 789', 'Chillán', 'Chillán', 'Chile', 'carlos.garcia@yahoo.com', 'Ninguna observación', '933345678', 1, 1, 1, 1),
('45678901-4', 'Ana Castillo', '2', 'Calle Sur 321', 'Los Ángeles', 'Los Ángeles', 'Chile', 'ana.castillo@gmail.com', 'Requiere seguimiento', '944345678', 1, 2, 1, 1),
('56789012-5', 'Pedro González', '3', 'Av. Norte 654', 'San Pedro', 'San Pedro', 'Chile', 'pedro.gonzalez@outlook.com', 'Sin observaciones', '955345678', 1, 3, 1, 1),
('67890123-6', 'Laura Díaz', '2', 'Paseo Central 987', 'Concepción', 'Concepción', 'Chile', 'laura.diaz@gmail.com', 'Cliente frecuente', '966345678', 1, 2, 1, 1),
('78901234-7', 'Jorge Silva', '1', 'Calle Esquina 147', 'Hualpén', 'Hualpén', 'Chile', 'jorge.silva@yahoo.com', 'Ninguna', '977345678', 1, 1, 1, 1),
('89012345-8', 'Elena Soto', '2', 'Avenida Industrial 258', 'Talcahuano', 'Talcahuano', 'Chile', 'elena.soto@gmail.com', 'Cliente nuevo', '988345678', 1, 2, 1, 1),
('90123456-9', 'Luis Fernández', '3', 'Camino Viejo 369', 'Coronel', 'Coronel', 'Chile', 'luis.fernandez@outlook.com', 'Pide descuentos', '999345678', 1, 3, 1, 1),
('11234567-0', 'Sofía Muñoz', '2', 'Calle Comercio 741', 'Concepción', 'Concepción', 'Chile', 'sofia.munoz@gmail.com', 'Sin observaciones', '912456789', 1, 2, 1, 1),
('12234567-1', 'Andrés Herrera', '1', 'Av. Independencia 852', 'Tomé', 'Tomé', 'Chile', 'andres.herrera@gmail.com', 'Cliente leal', '922456789', 1, 1, 1, 1),
('13234567-2', 'Camila Reyes', '3', 'Paseo Urbano 963', 'Lota', 'Lota', 'Chile', 'camila.reyes@hotmail.com', 'Solicita facturas', '932456789', 1, 3, 1, 1),
('14234567-3', 'Ricardo Ortiz', '2', 'Calle Norte 159', 'Arauco', 'Arauco', 'Chile', 'ricardo.ortiz@yahoo.com', 'Cliente habitual', '942456789', 1, 2, 1, 1),
('15234567-4', 'Gabriela Vargas', '1', 'Av. Universidad 951', 'Concepción', 'Concepción', 'Chile', 'gabriela.vargas@gmail.com', 'Cliente frecuente', '952456789', 1, 1, 1, 1),
('16234567-5', 'Manuel Vega', '3', 'Calle Pinos 753', 'San Pedro', 'San Pedro', 'Chile', 'manuel.vega@hotmail.com', 'Cliente de promoción', '962456789', 1, 3, 1, 1),
('17234567-6', 'Valentina Fuentes', '2', 'Paseo Laguna 357', 'Hualqui', 'Hualqui', 'Chile', 'valentina.fuentes@gmail.com', 'Recomienda amigos', '972456789', 1, 2, 1, 1),
('18234567-7', 'Pablo Morales', '1', 'Av. Peatonal 654', 'Concepción', 'Concepción', 'Chile', 'pablo.morales@outlook.com', 'Cliente satisfecho', '982456789', 1, 1, 1, 1),
('19234567-8', 'Fernanda Rojas', '3', 'Calle Industrial 258', 'Talcahuano', 'Talcahuano', 'Chile', 'fernanda.rojas@gmail.com', 'Cliente frecuente', '992456789', 1, 3, 1, 1),
('20234567-9', 'Daniel Cáceres', '2', 'Calle Lago 789', 'Chiguayante', 'Chiguayante', 'Chile', 'daniel.caceres@yahoo.com', 'Solicita cotización', '902456789', 1, 2, 1, 1),
('21234567-0', 'Claudia Pino', '1', 'Av. Central 963', 'Santa Juana', 'Santa Juana', 'Chile', 'claudia.pino@gmail.com', 'Cliente habitual', '912567890', 1, 1, 1, 1),
('22234567-1', 'Mario Figueroa', '3', 'Paseo Las Lomas 147', 'Concepción', 'Concepción', 'Chile', 'mario.figueroa@outlook.com', 'Recomienda servicios', '922567890', 1, 3, 1, 1),
('23234567-2', 'Isabel Morales', '2', 'Av. Italia 369', 'Chiguayante', 'Chiguayante', 'Chile', 'isabel.morales@gmail.com', 'Cliente leal', '932567890', 1, 2, 1, 1),
('24234567-3', 'Héctor Sandoval', '1', 'Calle Laguna 852', 'Hualpén', 'Hualpén', 'Chile', 'hector.sandoval@hotmail.com', 'Requiere seguimiento', '942567890', 1, 1, 1, 1),
('25234567-4', 'Carmen Araya', '3', 'Paseo Comercial 123', 'San Pedro', 'San Pedro', 'Chile', 'carmen.araya@gmail.com', 'Pide descuentos', '952567890', 1, 3, 1, 1),
('26234567-5', 'Felipe Guzmán', '2', 'Av. Las Palmeras 456', 'Coronel', 'Coronel', 'Chile', 'felipe.guzman@yahoo.com', 'Cliente nuevo', '962567890', 1, 2, 1, 1),
('27234567-6', 'Lorena Olivares', '1', 'Calle Universidad 789', 'Concepción', 'Concepción', 'Chile', 'lorena.olivares@gmail.com', 'Cliente satisfecho', '972567890', 1, 1, 1, 1),
('28234567-7', 'Roberto Jara', '3', 'Av. Andes 963', 'Talca', 'Talca', 'Chile', 'roberto.jara@hotmail.com', 'Ninguna', '982567890', 1, 3, 1, 1),
('29234567-8', 'Francisca Soto', '2', 'Calle Lago 147', 'Talcahuano', 'Talcahuano', 'Chile', 'francisca.soto@gmail.com', 'Cliente frecuente', '992567890', 1, 2, 1, 1),
('30234567-9', 'Cristóbal Rojas', '1', 'Av. Comercio 753', 'Chiguayante', 'Chiguayante', 'Chile', 'cristobal.rojas@outlook.com', 'Cliente leal', '902567890', 1, 1, 1, 1),
('31234567-0', 'Paola Salazar', '3', 'Paseo Norte 258', 'Concepción', 'Concepción', 'Chile', 'paola.salazar@gmail.com', 'Recomienda servicios', '912678901', 1, 3, 1, 1),
('32234567-1', 'Gonzalo Medina', '2', 'Av. Sur 654', 'San Pedro', 'San Pedro', 'Chile', 'gonzalo.medina@yahoo.com', 'Sin observaciones', '922678901', 1, 2, 1, 1),
('33234567-2', 'Tamara Sáez', '1', 'Calle Los Ríos 369', 'Hualpén', 'Hualpén', 'Chile', 'tamara.saez@gmail.com', 'Cliente habitual', '932678901', 1, 1, 1, 1),
('34234567-3', 'Fabián Parra', '3', 'Paseo Central 789', 'Chillán', 'Chillán', 'Chile', 'fabian.parra@hotmail.com', 'Cliente nuevo', '942678901', 1, 3, 1, 1),
('35234567-4', 'Beatriz Campos', '2', 'Av. Independencia 147', 'Concepción', 'Concepción', 'Chile', 'beatriz.campos@gmail.com', 'Sin observaciones', '952678901', 1, 2, 1, 1),
('36234567-5', 'Javiera Leiva', '1', 'Calle Universidad 852', 'Tomé', 'Tomé', 'Chile', 'javiera.leiva@hotmail.com', 'Solicita cotización', '962678901', 1, 1, 1, 1),
('37234567-6', 'Matías Miranda', '3', 'Av. Comercio 456', 'Hualqui', 'Hualqui', 'Chile', 'matias.miranda@gmail.com', 'Cliente habitual', '972678901', 1, 3, 1, 1),
('38234567-7', 'Alejandra Rivera', '2', 'Calle Comercio 951', 'Concepción', 'Concepción', 'Chile', 'alejandra.rivera@gmail.com', 'Cliente nuevo', '982678901', 1, 2, 1, 1);



INSERT INTO TIPO_PROVEEDOR (DESCRIPCION_TIPO_PROVEEDOR) VALUES
('Piezas'),
('Herramientas'),
('Suministros Generales'),
('Servicios de Transporte'),
('Servicios de Limpieza'),
('Maquinarias'),
('Materiales de Construcción');


INSERT INTO SUBMODULO (ID_MODULO, NOMBRE_SUBMODULO) VALUES (1, 'PROVEEDORES');
UPDATE SUBMODULO
SET NOMBRE_SUBMODULO = 'EMPLEADOS'
where ID_SUBMODULO = 5


SELECT * FROM SUBMODULO

INSERT INTO PANTALLAS_USUARIO (ID_USUARIO, ID_MODULO, ID_SUBMODULO)
VALUES
('USER_0', 1, 5)


-- Inserción en la tabla NOTIFICACIONES
INSERT INTO NOTIFICACIONES (
    TITULO_NOTIFICACION, 
    DESCRIPCION_NOTIFICACION, 
    ASUNTO_NOTIFICACION
) VALUES (
    'Bienvenida a la Plataforma', 
    'Nos complace darte la bienvenida. Esperamos que disfrutes de nuestros servicios.', 
    'Bienvenida'
);

INSERT INTO USUARIO_NOTIFICACION (
    ID_USUARIO, 
    ID_NOTIFICACION, 
    VISIBILIDAD_NOTIFICACION, 
    TIEMPO_ESPERA_NOTIFICACION
) VALUES 
    ('USER_0', 1, TRUE, 'Sin tiempo de espera'),
    ('USER_1', 1, TRUE, 'Sin tiempo de espera');