-- Tabla de Talleres --
CREATE TABLE taller (
    ID_TALLER VARCHAR(6) PRIMARY KEY,        
    NOM_TALLER VARCHAR(15),                 
    DIRECCION_TALLER VARCHAR(100),          
    COMUNA_TALLER VARCHAR(25),              
    CIUDAD_TALLER VARCHAR(25),              
    PAIS_TALLER VARCHAR(15),                
    CONTACTO_TALLER VARCHAR(20),            
    EMAIL_TALLER VARCHAR(25),               
    CAPT_VEHICULOS INT,                     
    FECHA_TALLER DATE ,      
    ESTADO_TALLER VARCHAR(10),              
    GERENTE_TALLER VARCHAR(15)              
);

-- Tabla de Modulos --
CREATE TABLE modulo	 (
  ID_MODULO BIGINT primary key generated always as identity,
  NOM_MODULO VARCHAR (15) NOT NULL,
  DESCRIPCION VARCHAR (30)
);

-- Tabla de Roles --
CREATE TABLE rol (
  ID_ROL BIGINT primary key generated always as identity,
  NOM_ROL VARCHAR (15) NOT NULL,
  DESCRIPCION VARCHAR (30)
);


-- Tabla de Permisos --
CREATE TABLE permiso (
  ID_PERMISO BIGINT primary key generated always as identity,
  NOM_PERMISO VARCHAR (15) NOT NULL,
  DESCRIPCION VARCHAR (30)
);

-- Tabla de roles y permisos --
create table rol_permiso (
  ID_ROL BIGINT REFERENCES rol (ID_ROL) ON DELETE CASCADE,
  ID_PERMISO BIGINT REFERENCES permiso (ID_PERMISO) ON DELETE CASCADE,
  PRIMARY KEY (ID_ROL, ID_PERMISO)
);

-- Tabla de Usuarios--
CREATE TABLE usuario (
	ID_USUARIO VARCHAR (7) PRIMARY KEY,
	EMAIL_USUARIO VARCHAR (25) UNIQUE,
	PASSWORD_USUARO VARCHAR (20),
	NOM_USUARIO VARCHAR (30),
	APEP_USUARIO VARCHAR (30),
	APEM_USUARIO VARCHAR (30),
	CONTAC_USUARIO VARCHAR (15),
	F_INGRESO_USUARIO VARCHAR (11),
	ESTADO_USUARIO VARCHAR (10),
	ID_ROL VARCHAR (3) REFERENCES rol (ID_ROL),
	ID_TALLER VARCHAR (6) REFERENCES taller (ID_TALLER)
)

-- Tabla de Modulos y permisos --
create table modulo_permiso (
  ID_MODULO BIGINT REFERENCES modulo (ID_MODULO) ON DELETE CASCADE,
  ID_PERMISO BIGINT REFERENCES permiso (ID_PERMISO) ON DELETE CASCADE,
  PRIMARY KEY (ID_MODULO, ID_PERMISO)
);


-- Tabla de usuarios y modulos --
create table usuario_modulo (
  ID_USUARIO BIGINT REFERENCES usuario (ID_USUARIO) ON DELETE CASCADE,
  ID_MODULO BIGINT REFERENCES modulo (ID_MODULO) ON DELETE CASCADE,
  PRIMARY KEY (ID_USUARIO, ID_MODULO)
);

-- Tabla de sucursales --
CREATE TABLE sucursal (
	ID_SUCURAL BIGINT primary key generated always as identity,
	NOM_SUCURSAL VARCHAR (50),
	DIRECION_SUCURSAL VARCHAR (100),
	COMUNA_SUCURSAL VARCHAR (25),
	CIUDAD_SUCURSAL VARCHAR (25),
	PAIS_SUCURSAL VARCHAR (15),
	TEL_SUCURSA VARCHAR (15),
	EMAIL_SUCURSAL VARCHAR (100),
	CAP_VEHICULOS_SUCURSAL INT,
	FECHA_SUCURSAL DATE DEFAULT SYSDATE,
	ID_TALLER VARCHAR (6) REFERENCES taller (ID_TALLER)
)

-- Tabla de Clientes --
CREATE TABLE cliente (
  ID_CLIENTE BIGINT generated always as identity,
  RUT_CLIENTE VARCHAR (10),
  PRIMARY KEY (ID_CLIENTE,RUT_CLIENTE),
  TIPO_CLIENTE VARCHAR (20),
  NOM_CLIENTE VARCHAR (100),
  TELMOVIL_CLIENTE VARCHAR (15),
  TELFIJO_CLIENTE VARCHAR (15),
  DIRECCION_CLIENTE VARCHAR (100),
  COMUNA_CLIENTE VARCHAR (25),
  CIUDAD_CLIENTE VARCHAR (25),
  PAIS_CLIENTE VARCHAR (15),
  EMAIL_CLIENTE VARCHAR (100), 
  ID_SUCURSAL BIGINT REFERENCES sucursal (ID_SUCURAL)
)

-- Tabla tipo de vehiculos --
CREATE TABLE tipo_vehiculo (
  ID_TIPOVEHICULO BIGINT generated always as identity,
  NOM_TIPOVEHICULO VARCHAR (20),
  DESCRIPCION_TIPOVEHICULO VARCHAR (100),
  PRIMARY KEY (ID_TIPOVEHICULO)
)
-- Tabla de Vehiculos --
CREATE TABLE vehiculo (
  ID_VEHICULO BIGINT generated always as identity,
  PATENTE_VEHICULO VARCHAR (6),
  PRIMARY KEY (ID_VEHICULO,PATENTE_VEHICULO),
  MARCA_VEHICULO VARCHAR (20),
  MODELO_VEHICULO VARCHAR (20),
  ANO_VEHICULO  INT,
  COLOR_VEHICULO VARCHAR (20),
  KILOMETRAJE_VEHICULO INT,
  MOTOR_VEHICULO VARCHAR (20),
  FECHA_VEHICULO DATE ,
  OBSERVACION_VEHICULO VARCHAR (100),
  ID_CLIENTE BIGINT REFERENCES cliente (ID_CLIENTE)
)